services:
  mysql:
    image: mysql:8.0
    container_name: projectmanager-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: projectmanager
      MYSQL_USER: app
      MYSQL_PASSWORD: app123
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -proot123"]
      interval: 5s
      timeout: 3s
      retries: 30

  app:
    build: .
    container_name: projectmanager-app
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker

      # (Opcional) puedes dejarlas si quieres, pero si ya tienes application-docker.properties son redundantes:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/projectmanager?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: app123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      SPRING_FLYWAY_ENABLED: "false"

      SECURITY_JWT_SECRET: change-me-super-secret-change-me-super-secret
      SECURITY_JWT_EXPIRATION_MINUTES: "120"

volumes:
  mysql_data:
